name: add1
on:
  push:
permissions:
  contents: write
  pull-requests: write
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: sh add.sh
      - uses: dev-hato/actions-diff-pr-management@cc201e3df74a342983025c4e97b7216b4e77f9f1 # v2.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          branch-name-prefix: fix-add1
          pr-title-prefix: add1
