name: add2
on:
  push:
permissions:
  contents: write
  pull-requests: write
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: sh add.sh
      - uses: dev-hato/actions-diff-pr-management@6d7a816ebc739dff9ca912882532c7b625cb2814
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          branch-name-prefix: fix-add1
          pr-title-prefix: add2
